apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logicmonitor-argus
  namespace: argocd
spec:
  destination:
    namespace: nttlogicmonitor
    server: 'https://kubernetes.default.svc'
  source:
    repoURL: 'https://raw.githubusercontent.com/Surinenc/surinenc_k8s/main/logicmonitor-helm/logicmonitor-argus-argocd/'
    targetRevision: 2.1.0
    chart: argus
    helm:
      valueFiles:
        - https://raw.githubusercontent.com/Surinenc/surinenc_k8s/main/logicmonitor-helm/logicmonitor-argus-argocd/values.yaml
  project: logicmonitor
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
