apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logicmonitor-argus
spec:
  destination:
    name: 'logicmonitor-argus'
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://logicmonitor.github.io/k8s-helm-charts'
    targetRevision: 2.1.0
    directory:
      recurse: true
    chart: argus
    helm:
      valueFiles:
        - values.yaml
  project: logicmonitor
  syncPolicy:
    automated: null
