apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-lm-helm
  namespace: argocd

spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: "nttlogicmonitor"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true

  sources:
  - repoURL: 'https://raw.githubusercontent.com/Surinenc/surinenc_k8s/main/lm-app-argocd/'
    chart: lm-container
    targetRevision: 7.0.0
    helm:
      valueFiles:
        #- secrets://secrets.yaml
        - 'secrets://https://raw.githubusercontent.com/Surinenc/surinenc_k8s/main/lm-app-argocd/secrets.yaml'
        # Method 1:
        #- secrets+gpg-import://helm-secrets-private-keys/key.asc?secrets.yaml
        #- 'secrets+gpg-import:///helm-secrets-private-keys/key.asc?https://raw.githubusercontent.com/Surinenc/surinenc_k8s/main/lm-app-argocd/secrets.yaml'
        # ### Method 2: Fetch the gpg key from kubernetes secret
        # secrets+gpg-import-kubernetes://<namespace>/<secret-name>#<key-name>.asc?<relative/path/to/the/encrypted/secrets.yaml>
        # secrets+age-import-kubernetes://<namespace>/<secret-name>#<key-name>.txt?<relative/path/to/the/encrypted/secrets.yaml>
        # Example Method 2: (Assumptions: namespace=argocd, secret-name=helm-secrets-private-keys, key-name=app, secret.yaml is in the root folder)
        #- secrets+gpg-import-kubernetes://argocd/helm-secrets-private-keys#key.asc?secrets.yaml
        #- secrets_unencrypted.yaml
        # - values.yaml
        #- https://raw.githubusercontent.com/Surinenc/surinenc_k8s/main/lm-app-argocd/secrets_unencrypted.yaml
        - https://raw.githubusercontent.com/Surinenc/surinenc_k8s/main/lm-app-argocd/values.yaml        

