---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret: AgBc7GysOwLwLPyV/Ot6p5xqR1C78hl59yUOI/gr8FvWXFzGB50cmj0Kz2DGZueLD0VGN7q9su9K4KiZBAZE8d4MN4FC4XYZckPevx3HFWytBbjQ1lqp8bW4M/sjhLbH1qzhWILX1vvtqdGbDkIcUjyAYSsOtyAjhPDzIeqNvhFecSyhKRmQnV3ryFzJqpFzs6rOfDe95hMI6PqPEo6iZsj4a2JbwI4CZkA1kyWH01KJCFY/kNQ+yasPDSy7vo+rt3i0ovqedkufZQSmpGAwtdznH1a+YvI0geEIUxzYUhW9Yts2EGGxwR8haq2AElcV+41NLW14K7KZh9cwKomkQgO4Rk5E8GBodpoXSOaIXii8Q83Weq5a4Myw7DxCFD5QW6q5YDcxeDwOb7sOhzjgxBezfdsjthzt+4oAQX39Pocpmk3Zqb0zNN2yLpdKrkEYmvb/6h2NoTb43+7YwDOdmJ+T+R3SogwOtuGZk3TMBnv7qVUCxqt+uknEzGm+I2JBBYs51evqgGDBvFnWuJNEaRTm4pI3EUsByoor7X5UuQzFkKoEGWTrjj1aM/idvv38z8T4bMPj+ibu7CemoV7dzdusfW9rDgSV3qmAnrrs5Afdq1IkX7tyA+4UtN5oxxekpy8G2rnGDwGK9iqc4ME8zoM9/qk4uWwpjvlWDrqEgz8asSdEXJPAVtze5+m4IbNite/HN3+c/uReBEbnj+L4hn0=
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
