global:
  accessID: ""
  accessKey: ""
  account: ""
  userDefinedSecret: "user-provided-secret"

argus:
  clusterName: "k8c00000000666-lm-argocd-app"
  enabled: true
  collector:
    size: "medium"
    lm:
      groupID: 185
      escalationChainID: 1
  rbac:
    create: true
  clusterTreeParentID: 117579
  resourceContainerID: 117580
  selfMonitor:
    enable: true
  monitoring:
    disable:
      - daemonsets
      - cronjobs
      - endpoints
      - persistentvolumeclaims
      - jobs
      - horizontalpodautoscalers
  filters:
      - type in ("pod", "deploy", "service", "deployment","replicaset","statefulset") && namespace != "nttlogicmonitor"
      - '!(type in ("node","pod", "deploy", "service", "deployment","replicaset","statefulset"))'


collectorset-controller:
  enabled: true
  probe:
      enabled: true
      grpcContainerProbeEnabled: false

# Kube state metrics configuration
# For further customizing KSM configuration, pls refer https://artifacthub.io/packages/helm/prometheus-community/kube-state-metrics/?modal=values
kube-state-metrics:
  # Set enabled to false in case you want to use a custom configured KSM
  enabled: true
  # No. of KSM Replicas to be configured
  selfMonitor:
    enabled: true
    telemetryPort: 8081
  replicas: 1
  collectors:
    - daemonsets
    - replicasets
    - statefulsets
    - persistentvolumes
    - persistentvolumeclaims
    - endpoints
    - cronjobs
    - jobs
    - pods
    - nodes
    - deployments
    - services
    - poddisruptionbudgets